### ISSUE TITLE
 There is insufficient memory for the Java Runtime Environment to continue.

### ISSUE THREAD

**Issue by BhavaniKalakota** [SonarSource/docker-sonarqube#640] opened 2023-09-11 11:40 UTC
Hello, Please help us with this issue, this issue started happening from last latest 4 weeks.
OS : Windows
CPU cores: 6
RAM memory: 32 GB
docker: yes

There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log

`bhavanik@bhavanik MINGW64 ~
$ winpty docker run -it --rm -p 9000:9000  --name sonarqube_-Xmx1g sonarqube:latest -Dsonar.search.javaAdditionalOpts=-Xmx3g
Unable to find image 'sonarqube:latest' locally
latest: Pulling from library/sonarqube
44ba2882f8eb: Pull complete
2cabec57fa36: Pull complete
c20481384b6a: Pull complete
bf7b17ee74f8: Pull complete
38617faac714: Pull complete
b795b715553d: Pull complete
c5244f6c9231: Pull complete
Digest: sha256:1ffd122cfb37ce982289dc7f5d38bb702ba05af7b5a50f7cb077ae25e60b5b9a
Status: Downloaded newer image for sonarqube:latest
[0.005s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k
, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log

bhavanik@bhavanik MINGW64 ~
$ winpty docker run -it --rm -p 9000:9000  --name sonarqube_mmapfs sonarqube:latest -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false
[0.007s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k
, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log

bhavanik@bhavanik MINGW64 ~
$ winpty docker run -it --rm -p 9000:9000  --name sonarqube sonarqube:latest
[0.008s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k
, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
`

**Comment by skoch98** [comment] 2023-10-11 11:17
I'm able to reproduce this:

 - `docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest`
 - `docker ps -a` -> `Exited (1) 6 seconds ago`
 - `docker logs sonarqube` returned:
```
[0.002s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
```

----

Server-Information:
Linux vm-docker 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64 GNU/Linux
Docker version 19.03.14, build 5eb3275d40
CPU cores: 4
RAM: 32 GB

---

I decided to update the distribution and docker first because Debian 9 is EOL. After that I will see.
For testing the basics, as long as I haven't updated Debian yet, I use an old version that works to check if the tool is suitable for us.: `docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:8.9.6-community`

**Comment by skoch98** [comment] 2023-10-13 11:43
### Update to my comment: https://github.com/SonarSource/docker-sonarqube/issues/640#issuecomment-1757457920

After I updated Linux and Docker the latest version of sonarqube works fine for me.

```
Linux vm-docker 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux
Docker version 24.0.6, build ed223bc
```

@BhavaniKalakota I recommend you to update docker aswell - if available.

**Comment by jCOTINEAU** [comment] 2023-11-22 14:35
Hello everyone, glad to hear that the issue has been solved, i will proceed and close this.

Nonetheless if there is still a need or an un-answered question then please create a new thread in our [forum](https://community.sonarsource.com/tags/c/sq/10/none/docker).

It will ease a lot the triaging process.

**Closed by jCOTINEAU** 2023-11-22 14:35 UTC

**Comment by nhutwkm** [comment] 2024-10-11 01:53
run docker with `--privileged`
```
docker run \
  --name sonarqube \
  --privileged \
  -p 9000:9000 \
  sonarqube
````
