### ISSUE TITLE
No longer able to run sonarqube:9.3.0-community

### ISSUE THREAD

**Issue by alexsuter** [SonarSource/docker-sonarqube#544] opened 2022-04-01 10:10 UTC
I'm no longer able to start a plain `sonarqube:9.3.0-community` container. 

```
docker run sonarqube:9.3.0-community
```

I always get the same stacktrace. I was able to run this container since two weeks. Then I think we have auto-updated the container fetching a new build of this image.

```
Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=1deafca2 actual=c351dc41 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/opt/sonarqube/data/es7/nodes/0/_state/_11.fdt")))
sonarqube_1  | 	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:419) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:100) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:55]
sonarqube_1  | 	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:5313) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:457) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:395) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:476) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:656) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.IndexWriter.doFlush(IndexWriter.java:3911) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3886) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3865) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
sonarqube_1  | 	at org.elasticsearch.gateway.PersistedClusterStateService$MetadataIndexWriter.flush(PersistedClusterStateService.java:611) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.addMetadata(PersistedClusterStateService.java:884) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.overwriteMetadata(PersistedClusterStateService.java:858) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeFullStateAndCommit(PersistedClusterStateService.java:705) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.<init>(GatewayMetaState.java:515) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:170) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.node.Node.start(Node.java:1185) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.16.3.jar:7.16.3]
sonarqube_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.16.3.jar:7.16.3]
```

**Comment by alexsuter** [comment] 2022-04-01 10:37
Sonarqube 9.2.0 seems to work properly.

**Comment by morzan1001** [comment] 2022-04-05 10:10
I have the same problem. Today Sonarqube 9.4.0 was released, but also here the container can not be started due to the error of the Elastic Search database :( . There is already a question about this at SonarCommunity: https://community.sonarsource.com/t/updating-sonarqube-via-docker-compose/60955/4

**Comment by alexsuter** [comment] 2022-04-05 12:40
Maybe this problem is somehow connected to our virtualization layer. On my local machine without a virtual machine the container runs.

**Comment by klaudio-sinani-sonarsource** [comment] 2022-04-05 12:58
@alexsuter Thank you for taking the time to report the issue. 
Could you try clearing your es indexes and try again?

**Comment by morzan1001** [comment] 2022-04-05 13:03
@klaudio-sinani-sonarsource I have deleted the folder `es7` in the data directory of the container. This folder was then created again at the next start, but unfortunately this did not change the error message.

**Comment by KalinaLadnay** [comment] 2022-04-05 13:06
I try images 9.3.0-community, 9.4.0-community, 9.2.4-community and 9.2.4-developer. Same problem with elastic. I run them on kubernetes cluster which installed on virtual machines. I don't want use images older than 9.2.0 because they have Log4Shell CVE

**Comment by KalinaLadnay** [comment] 2022-04-05 13:57
I uncresed heap size for Elastic and it works for me.
sonar.search.javaOpts=-Xms1024m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError

**Comment by alexsuter** [comment] 2022-04-05 14:49
> @alexsuter Thank you for taking the time to report the issue. Could you try clearing your es indexes and try again?

I cleaned the Elasticsearch indices multiple times. No success.

I think this has something to do with your base image. Since the rebuild of this image `sonarqube:9.3.0-community` on last Wednesday the container no longer worked. But you did not change the `Dockerfile` then - so I guess something changed in the base image?

**Comment by karljohns0n** [comment] 2022-04-07 17:53
I've been struggling with this for an hour. I have exactly the same issue with 9.3 and 9.4.

**Comment by Nazardo** [comment] 2022-04-08 07:09
I have been facing the exact same issue reported here by @alexsuter and @karljohns0n.

I have been able to obtain a working container running version 9.4 with the following two steps:

- delete `es7` folder in the data directory;
- replace the base **alpine** image with the older 3.14.3 and rebuild the docker image locally (`FROM alpine:3.14.3`).

The problem exists both with alpine 3.14.5 and with the latest 3.14.6.

**Comment by karljohns0n** [comment] 2022-04-10 14:36
I found this thread https://github.com/elastic/elasticsearch/issues/85546#issuecomment-1089627067. I switched the CPU model and now SonarQube 9.4 is working.

**Comment by alexsuter** [comment] 2022-04-11 06:17
Thanks @karljohns0n ! We run our virtualization on proxmox too! I'll ceck this next week my colleague @ivy-cst

**Comment by morzan1001** [comment] 2022-04-11 14:35
Thanks @karljohns0n for sharing this elasticsearch Issue. Unfortunately my server is too old to support `Haswell`,` but i tried `SandyBridge` which works fine. So it seems to be a problem of elasticsearch in connection with `kvm64` architetur.

**Comment by karljohns0n** [comment] 2022-04-11 14:38
Yes kvm64 seems to miss some CPU flags so I switch the model to Host to be 1:1.

**Comment by MartijnErmersI** [comment] 2022-04-12 12:24
> I have been facing the exact same issue reported here by @alexsuter and @karljohns0n.
> 
> I have been able to obtain a working container running version 9.4 with the following two steps:
> 
> * delete `es7` folder in the data directory;
> * replace the base **alpine** image with the older 3.14.3 and rebuild the docker image locally (`FROM alpine:3.14.3`).
> 
> The problem exists both with alpine 3.14.5 and with the latest 3.14.6.

I've tried this solution for 8.9.8 LTS and **didn't get it to work** for the following Alpine versions:
- 3.12.9 (The one shipped with 8.9.7 LTS)
- 3.12.12 (The latest 3.12 version)
- 3.14.3 (The one suggested as a fix)

Our wrapper image always deletes the es7 folder prior to starting the SonarQube process, so that isn't the problem.

**Comment by dm-ion** [comment] 2022-04-12 19:31
Hi this issue is specific to ZLib, which was upgraded in various version of alpine.

Your workaround is to build your own docker for Sonar on an older alpine version until you can upgrade your CPU.

So any alpine version after (and including) these you may have some Zip CRC issues, or issues with elastic search checksums it seems:
3.12.11
3.13.9
3.14.5
3.15.3

**Comment by djsparrow** [comment] 2022-05-02 15:17
For AMD processor that are older, for me, I put on proxmox the CPU to "host" and setting the SonarQube image to latest. Worked just fine for me...

**Comment by pschyska** [comment] 2022-05-13 14:22
This patch fixed it for me:
```diff
From d65848c22ff8d64fdb05161a50f568098580d4d8 Mon Sep 17 00:00:00 2001
From: Paul Schyska <Paul.Schyska@akquinet.de>
Date: Fri, 13 May 2022 16:09:10 +0200
Subject: [PATCH] Upgrade zlib to 1.2.12-r1, which includes crc32.patch

Fixes: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?)

https://github.com/alpinelinux/aports/commit/6754a9005594de4243aad9b2744546971078c6c7
---
 9/community/Dockerfile | 1 +
 1 file changed, 1 insertion(+)

diff --git a/9/community/Dockerfile b/9/community/Dockerfile
index 72ba7a4..b1adf01 100644
--- a/9/community/Dockerfile
+++ b/9/community/Dockerfile
@@ -21,6 +21,7 @@ ENV JAVA_HOME='/usr/lib/jvm/java-11-openjdk' \
 RUN set -eux; \
     addgroup -S -g 1000 sonarqube; \
     adduser -S -D -u 1000 -G sonarqube sonarqube; \
+    apk add --no-cache --upgrade 'zlib>=1.2.12-r1'; \
     apk add --no-cache --virtual build-dependencies gnupg unzip curl; \
     apk add --no-cache bash su-exec ttf-dejavu openjdk11-jre; \
     # pub   2048R/D26468DE 2015-05-25
--
2.36.0
```

**Comment by joelsdc** [comment] 2022-05-20 02:55
We are facing the same issue here.

I tested the [workaround 1](https://github.com/SonarSource/docker-sonarqube/issues/544#issuecomment-1092517489) posted by @Nazardo and it worked for me.

I then went ahead and tested the [workaround 2](https://github.com/SonarSource/docker-sonarqube/issues/544#issuecomment-1126115911) posted by @pschyska and it also worked.

I'm sticking for now with the latter, as of today (after the patch of May 13th) I believe it to be better, thanks for sharing!

**Comment by jonesbusy** [comment] 2022-05-31 09:35
Hi,

Also same issue here with sonarqube:9.4.0-community

Environment with Sonarqube using Helm chart on OKD.

I needed to extends the official image for this to work.

Hope it will included on next releases

```
FROM sonarqube:9.4.0-community
USER root
RUN apk add --no-cache --upgrade 'zlib>=1.2.12-r1';
USER sonarqube
```

Regards,

**Comment by thelooter** [comment] 2022-06-19 20:31
Is this issue gonna get a fix merged or do we have to build the image ourself going forward?

**Comment by mstaessen** [comment] 2022-06-28 15:11
You can fix it without building the image yourself by upgrading zlib in the running container, but a more permanent fix is still much desired.

    docker exec -it sonarqube /bin/bash

And then run

    apk add --no-cache --upgrade 'zlib>=1.2.12-r1'

**Comment by djdembeck** [comment] 2022-06-30 22:54
I have this issue with `8-community` and `9-community` as well.

**Comment by tahaar** [comment] 2022-07-04 11:48
I'm also facing this issue when trying to run sonarqube:8.9-community inside virtual machine.
Latest image works with "RUN apk add --no-cache --upgrade 'zlib>=1.2.12-r1';".

Problem is that I cannot use the latest, I need java8 for the the maven plugin (scanner).

**Comment by ardevd** [comment] 2022-07-21 14:42
How is this issue still not fixed in the official docker images is beyond me. The bug has persisted across multiple versions now.

**Comment by thelooter** [comment] 2022-07-21 15:25
My guess is that they want to wait for Zlib to fix it themselves, and can take quite some time

**Comment by wouter-admiraal-sonarsource** [comment] 2022-07-29 13:31
Hi all,

Sorry for the late reply, and delay in dealing with this. We were waiting on Alpine to publish a new version of 3.14 which would include this fix + some other one we were waiting on. I'll update our base image today. This should trigger a rebuild and re-publishing on `latest`, and in any case it will be part of the upcoming 9.6 version.

**Closed by wouter-admiraal-sonarsource** 2022-07-29 13:31 UTC

**Comment by mqu** [comment] 2022-08-03 08:56
hello, I a still facing same issue, about zlib + CRC even with lastest dockerised Sonar version (9.5).
- issue occures on VM (proxmox) but do not on non virtualised hosts.


```
admin@intra:~$ docker run --rm -it sonarqube:9.5-community
...
2022.08.03 08:46:45 ERROR es[][o.e.b.ElasticsearchUncaughtExceptionHandler] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to load metadata]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=92d1d1af actual=4c6af14c (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/opt/sonarqube/data/es7/nodes/0/_state/_0.fdt")))];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.1.jar:7.17.1]
	at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.1.jar:7.17.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.1.jar:7.17.1]
Caused by: org.elasticsearch.ElasticsearchException: failed to load metadata
	at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:214) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.node.Node.start(Node.java:1188) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.1.jar:7.17.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.1.jar:7.17.1]


admin@intra:~$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1000065
cpu MHz		: 2645.030
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm rep_good nopl cpuid extd_apicid tsc_known_freq pni cx16 x2apic hypervisor cmp_legacy 3dnowprefetch vmmcall
bugs		: fxsave_leak sysret_ss_attrs null_seg swapgs_fence spectre_v1 spectre_v2
bogomips	: 5290.06
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by mqu** [comment] 2022-08-03 13:13
under proxmox, when I configure VM with CPU=host, this command is OK.
```
docker run --rm -it sonarqube:9.5-community
```
- now, need to find wich CPU flags are mandatory or CPU familly.

**Comment by mqu** [comment] 2022-08-03 14:35
I can confirm : 
- this one is OK even in virtualised environment
```
FROM sonarqube:9.5-community
USER root
RUN apk add --no-cache --upgrade 'zlib>=1.2.12-r1';
USER sonarqube
```
then run 
```
docker build -t sonarqube:9.5-custom .
docker run --rm -it sonarqube:9.5-custom
```
- trying with latest LTS (8.9.9), it does not work .

**Comment by Nazardo** [comment] 2022-10-28 08:30
I think this issue may have been resolved upstream, because I did not have to patch the latest image with the `zlib` upgrade.
