### ISSUE TITLE
After container restart quality rules disappear

### ISSUE THREAD

**Issue by ranying666** [SonarSource/docker-sonarqube#75] opened 2017-04-17 10:23 UTC
sonarqube:6.1  
First time start container everythis is ok.  
When I restart container,all quality rules disappear.  
But scan results still exist.  
Why？
Dockerfile：
VOLUME "/opt/sonarqube/data"

**Comment by jonmosco** [comment] 2017-07-12 12:13
I am experiencing this issue as well with 5.6.6 LTS.

**Comment by Godin** [comment] 2017-07-13 10:41
@ranying666 @jonmosco What are the **exact steps** to reproduce this?

I'm asking because can't reproduce:
```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sonarqube           5.6.6               87a7536c1a6b        5 days ago          872MB

$ docker run -d --name sonarqube -p 9000:9000 sonarqube:5.6.6

$ docker restart sonarqube

$ docker stop sonarqube

$ docker start sonarqube

$ docker logs sonarqube | grep -E "Web server is (stopped|started)"
2017.07.13 10:29:33 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2017.07.13 10:31:14 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2017.07.13 10:31:46 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2017.07.13 10:32:12 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2017.07.13 10:32:52 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
```

Rules are shown in UI as well as in query of web service after such restarts:
```
$ curl http://localhost:9000/api/rules/search | grep -E -o "\"total\":[0-9]*"
"total":913
```

**Comment by simonbrandhof** [comment] 2017-07-26 07:42
The thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sonarqube/tnSz1ugaYf0/XFjuuu-NBwAJ provides more details. To sum-up:
- unexpected shutdown may come from Azure
- plugins should be extracted from the container by mapping the directory extensions/plugin outside the container. That deserves the directory to be published in Dockerfile as a volume.

**Comment by Godin** [comment] 2017-07-26 12:41
@simonbrandhof thank you for the information about Azure.

Regarding

> plugins should be extracted from the container by mapping the directory extensions/plugin outside the container. That deserves the directory to be published in Dockerfile as a volume.

We removed declaration of volume for directory `extensions` in 80366e3419d698b4bba4447f153418ef64b3b705 for the very good reasons after discussion in https://github.com/docker-library/official-images/pull/2437#issuecomment-266578986

And AFAIK absence of explicit declaration of volume does not prevent externalization of this directory:

```
$ docker run -v /tmp/sonarqube/extensions:/opt/sonarqube/extensions sonarqube
```

or using `docker-compose`:
```
version: "2"

services:
  sonarqube:
    image: sonarqube
    volumes:
      - ./extensions:/opt/sonarqube/extensions
```

So I'm closing this ticket.

In case of problems with infrastructure (as with Azure), please consider contacting service provider.

**Closed by Godin** 2017-07-26 12:41 UTC
Labels: invalid
