### ISSUE TITLE
FATAL: password authentication failed for user "sonar" 

### ISSUE THREAD

**Issue by larruda** [SonarSource/docker-sonarqube#81] opened 2017-05-12 00:41 UTC
After upgrading to 6.1, 6.2, 6.3 or 6.3.1 images (alpine or not), my instance keeps failing with this message. The password is correct and available through the SONARQUBE_JDBC_PASSWORD environment variable set as a secret in Kubernetes. If I go back to 6.0, it just works. 

Did something change regarding connecting to the database?

**Comment by jarrod268** [comment] 2017-05-30 12:30
Having the same problem as well.

**Comment by Godin** [comment] 2017-05-30 16:55
Cannot reproduce using PostgreSQL:
```
docker run -it --rm --name some-postgres \
  -e POSTGRES_USER=myuser \
  -e POSTGRES_PASSWORD=mysecretpassword \
  -e POSTGRES_DB=sonar \
  postgres

docker run -it --rm --name sonarqube \
  -p 9000:9000 \
  --link some-postgres:postgres \
  -e SONARQUBE_JDBC_USERNAME=myuser \
  -e SONARQUBE_JDBC_PASSWORD=mysecretpassword \
  -e SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar \
  sonarqube:6.3.1-alpine
```
second container with SonarQube 6.3.1 successfully connects to the first one.


Answering on the question
> Did something change regarding connecting to the database?

This repository contains files to build Docker image for SonarQube and nothing more, i.e. not the SonarQube itself. The only changes in this repository between image for 6.0 and image for 6.3.1 are updates of SonarQube version - https://github.com/SonarSource/docker-sonarqube/compare/5dc27334bbf784f63f209e83b2c9b9023a75ee7f...476d459572e062e8e005647cc82e9f322f7a4b52 About the changes in SonarQube itself please refer to its repository changelog/release notes/upgrade notes. But AFAIK there were no changes in regards to database connection. For the questions about SonarQube you'd better reach out to wider audience of community - there are various communication channels, such as Google Group: https://www.sonarqube.org/community/

In absence of clear steps to reproduce the issue and hence evidences that there is a problem specifically in files for image and not in a particular setup/environment, I'm closing this ticket.

Thank you for your understanding.

**Closed by Godin** 2017-05-30 16:55 UTC

**Comment by larruda** [comment] 2017-05-30 17:23
@jarrod268 please let me know if somehow you find to solve the issue.
Thanks @Godin for the explanation.

**Comment by jarrod268** [comment] 2017-05-30 18:05
This works fine on a VM with the latest version of docker-compose, however the Azure extension for docker is behind a little on the docker-compose version and they may be the culprit for me.
