### ISSUE TITLE
Unable to execute SonarQube: Fail t o get bootstrap index from server

### ISSUE THREAD

**Issue by LionHeart7735** [SonarSource/docker-sonarqube#219] opened 2018-11-28 02:14 UTC
Hi All,

I using docker toolbox run with docker-compose 
The docker-compose run successfully and I able to generate the token from sonar console
I use this token to analyze maven project with below command 

`mvn sonar:sonar -Dsonar.host.url=http://192.168.99.100:9000 -Dsonar.login=492b3385eb6f0a2b2c102c43897b56d34c78e7ad`

But i having below error 
[Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project gpcsbq: Unable to execute SonarQube: Fail t
o get bootstrap index from server: Status returned by url [http://192.168.99.100:9000/batch/index] is not valid: [503] -> [Help 1]

Appreciate for any advice

Jason

**Comment by janos-ss** [comment] 2018-11-30 09:10
Does that happen repeatedly, consistently? 503 indicates a server side error that's supposed to be temporary. 

If this happens repeatedly, please show us some logs. Look in the `/opt/sonarqube/logs` folder. There should be error messages in some of the logs.

**Comment by Savemech** [comment] 2018-12-09 18:05
For me this is happens repeatedly
and I did notice really weird thing, if i go for 
`docker run -it -v /repo-path/:/buildzone maven:alpine sh`
and then 
`mvn -X clean verify package sonar:sonar -f pom.xml  -Dsonar.login=<token> -Dsonar.host.url=https://sonar.yes.fancy-host.com -DskipTests`
That works absolutely fine
Here is log from raw `docker build .`
steps described in Dockerfile is 
```
FROM maven:alpine as buildstage
ARG MAVEN_OPTS="-Xmx4096m"
ADD . /root/build-zone/
ADD settings.xml /root/.m2/settings.xml
ADD settings-security.xml /root/.m2/settings-security.xml
WORKDIR /root/build-zone/
RUN mvn -X clean verify package sonar:sonar -f pom.xml  -Dsonar.login=<token>-Dsonar.host.url=https://sonar.yes.fancy-host.com -DskipTests


```
```
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=36102, ConflictMarker.markTime=42610, ConflictMarker.nodeCount=7, ConflictIdSorter.graphTime=15455, ConflictIdSorter.topsortTime=22151, ConflictIdSorter.conflictIdCount=6, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=79351, ConflictResolver.conflictItemCount=7, DefaultDependencyCollector.collectTime=243481939, DefaultDependencyCollector.transformTime=268632}
[DEBUG] org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.5.0.1254:
[DEBUG]    org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
[DEBUG]       org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
[DEBUG]    org.sonarsource.scanner.api:sonar-scanner-api:jar:2.10.0.1189:compile
[DEBUG]    commons-lang:commons-lang:jar:2.6:compile
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods with username=lp-buildagent-01, password=***
[INFO] Downloading from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[INFO] Downloading from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[INFO] Downloading from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/org/sonarsource/scanner/api/sonar-scanner-api/2.10.0.1189/sonar-scanner-api-2.10.0.1189.jar
[INFO] Downloading from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[INFO] Downloaded from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar (28 kB at 1.3 MB/s)
[INFO] Downloaded from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar (245 kB at 4.2 MB/s)
[INFO] Downloaded from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/commons-lang/commons-lang/2.6/commons-lang-2.6.jar (284 kB at 3.9 MB/s)
[INFO] Downloaded from somefancy-artifactory: https://some.fancy.artifactory.out.there.com/artifactory/vrt_repo_with_some_goods/org/sonarsource/scanner/api/sonar-scanner-api/2.10.0.1189/sonar-scanner-api-2.10.0.1189.jar (582 kB at 6.8 MB/s)
[DEBUG] Writing tracking file /tmp/mvn_repo/org/sonatype/plexus/plexus-sec-dispatcher/1.4/_remote.repositories
[DEBUG] Writing tracking file /tmp/mvn_repo/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar.lastUpdated
[DEBUG] Writing tracking file /tmp/mvn_repo/org/codehaus/plexus/plexus-utils/3.0.22/_remote.repositories
[DEBUG] Writing tracking file /tmp/mvn_repo/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar.lastUpdated
[DEBUG] Writing tracking file /tmp/mvn_repo/org/sonarsource/scanner/api/sonar-scanner-api/2.10.0.1189/_remote.repositories
[DEBUG] Writing tracking file /tmp/mvn_repo/org/sonarsource/scanner/api/sonar-scanner-api/2.10.0.1189/sonar-scanner-api-2.10.0.1189.jar.lastUpdated
[DEBUG] Writing tracking file /tmp/mvn_repo/commons-lang/commons-lang/2.6/_remote.repositories
[DEBUG] Writing tracking file /tmp/mvn_repo/commons-lang/commons-lang/2.6/commons-lang-2.6.jar.lastUpdated
[DEBUG] Created new class realm plugin>org.codehaus.mojo:sonar-maven-plugin:3.5.0.1254
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:sonar-maven-plugin:3.5.0.1254
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.codehaus.mojo:sonar-maven-plugin:3.5.0.1254
[DEBUG]   Included: org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.5.0.1254
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.22
[DEBUG]   Included: org.sonarsource.scanner.api:sonar-scanner-api:jar:2.10.0.1189
[DEBUG]   Included: commons-lang:commons-lang:jar:2.6
[DEBUG] Configuring mojo org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar from plugin realm ClassRealm[plugin>org.codehaus.mojo:sonar-maven-plugin:3.5.0.1254, parent: sun.misc.Launcher$AppClassLoader@70dea4e]
[DEBUG] Configuring mojo 'org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar' with basic configurator -->
[DEBUG]   (f) mojoExecution = org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar {execution: default-cli}
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6f3f0fae
[DEBUG]   (f) skip = false
[DEBUG] -- end configuration --
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] 10:34:23.907 keyStore is : 
[DEBUG] 10:34:23.909 keyStore type is : jks
[DEBUG] 10:34:23.909 keyStore provider is : 
[DEBUG] 10:34:23.909 init keystore
[DEBUG] 10:34:23.910 init keymanager of type SunX509
[DEBUG] 10:34:23.918 Create: /root/.sonar/cache
[INFO] 10:34:23.920 User cache: /root/.sonar/cache
[DEBUG] 10:34:23.920 Create: /root/.sonar/cache/_tmp
[DEBUG] 10:34:23.923 Extract sonar-scanner-api-batch in temp...
[DEBUG] 10:34:23.928 Get bootstrap index...
[DEBUG] 10:34:23.929 Download: https://sonar.yes.fancy-host.com/batch/index
[ERROR] 10:34:24.192 SonarQube server [https://sonar.yes.fancy-host.com] can not be reached
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.416 s
[INFO] Finished at: 2018-12-09T10:34:24Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project lpconsole: Unable to execute SonarQube: Fail to get bootstrap index from server: Status returned by url [https://sonar.yes.fancy-host.com/batch/index] is not valid: [503] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project lpconsole: Unable to execute SonarQube
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute SonarQube
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:67)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:104)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarQube
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0 (IsolatedLauncherFactory.java:85)
    at java.security.AccessController.doPrivileged (Native Method)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher (IsolatedLauncherFactory.java:74)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher (IsolatedLauncherFactory.java:70)
    at org.sonarsource.scanner.api.EmbeddedScanner.doStart (EmbeddedScanner.java:167)
    at org.sonarsource.scanner.api.EmbeddedScanner.start (EmbeddedScanner.java:113)
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:56)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:104)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IllegalStateException: Fail to get bootstrap index from server
    at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex (BootstrapIndexDownloader.java:42)
    at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles (JarDownloader.java:58)
    at org.sonarsource.scanner.api.internal.JarDownloader.download (JarDownloader.java:53)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0 (IsolatedLauncherFactory.java:76)
    at java.security.AccessController.doPrivileged (Native Method)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher (IsolatedLauncherFactory.java:74)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher (IsolatedLauncherFactory.java:70)
    at org.sonarsource.scanner.api.EmbeddedScanner.doStart (EmbeddedScanner.java:167)
    at org.sonarsource.scanner.api.EmbeddedScanner.start (EmbeddedScanner.java:113)
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:56)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:104)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IllegalStateException: Status returned by url [https://sonar.yes.fancy-host.com/batch/index] is not valid: [503]
    at org.sonarsource.scanner.api.internal.ServerConnection.callUrl (ServerConnection.java:115)
    at org.sonarsource.scanner.api.internal.ServerConnection.downloadString (ServerConnection.java:98)
    at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex (BootstrapIndexDownloader.java:39)
    at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles (JarDownloader.java:58)
    at org.sonarsource.scanner.api.internal.JarDownloader.download (JarDownloader.java:53)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0 (IsolatedLauncherFactory.java:76)
    at java.security.AccessController.doPrivileged (Native Method)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher (IsolatedLauncherFactory.java:74)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher (IsolatedLauncherFactory.java:70)
    at org.sonarsource.scanner.api.EmbeddedScanner.doStart (EmbeddedScanner.java:167)
    at org.sonarsource.scanner.api.EmbeddedScanner.start (EmbeddedScanner.java:113)
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:56)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:104)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command '/bin/sh -c mvn -X clean verify package sonar:sonar -f pom.xml  -Dsonar.login=755d6873e9cb03a036d20da928b1721631376977 -Dsonar.host.url=https://sonar.yes.fancy-host.com -DskipTests' returned a non-zero code: 1
```
And again, when manually do all the stuff that described in Dockerfile with `docker run`, all works fine.

**Comment by Savemech** [comment] 2018-12-11 13:03
Well my problem is incorrectly configured ingress on K8S.

**Comment by janos-ss** [comment] 2019-01-07 14:40
@Savemech I don't see how that's related to the issue in the first post. Can you please enlighten?

**Comment by Savemech** [comment] 2019-01-10 12:07
@janos-ss  Yeah, basically I just got same errors as @LionHeart7735, but then after double check everything I found that nothing wrong with sonarqube, it is misconfiguration of ingress controller that expose sonarqube application from K8S cluster.

**Comment by qintang** [comment] 2019-01-13 08:59
i having below error. i can connect 10.24.16.15:9000

[ERROR] 16:50:06.046 SonarQube server [http://10.24.16.15:9000] can not be reached
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.287 s
[INFO] Finished at: 2019-01-13T16:50:06+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project workflow-monitor: Un
able to execute SonarQube: Fail to get bootstrap index from server: connect timed out -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:son
ar (default-cli) on project workflow-monitor: Unable to execute SonarQube
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)

**Comment by cforce** [comment] 2019-03-27 13:49
same here

**Comment by jasiellp** [comment] 2019-03-29 20:56
opa

**Comment by pierre-guillot-sonarsource** [comment] 2019-07-16 11:54
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.

**Closed by pierre-guillot-sonarsource** 2019-07-16 11:54 UTC

**Comment by chiducaf** [comment] 2021-02-25 13:03
Duplicate of #

**Comment by chen-jie** [comment] 2022-08-10 08:18
> @janos-ss Yeah, basically I just got same errors as @LionHeart7735, but then after double check everything I found that nothing wrong with sonarqube, it is misconfiguration of ingress controller that expose sonarqube application from K8S cluster.

Got the same iusse while expose sonarqube application through ingress controller from K8S cluster.
Do you still remember how to fix this?

**Comment by chen-jie** [comment] 2022-08-10 08:19
> @janos-ss Yeah, basically I just got same errors as @LionHeart7735, but then after double check everything I found that nothing wrong with sonarqube, it is misconfiguration of ingress controller that expose sonarqube application from K8S cluster.

@Savemech 
Got the same iusse while expose sonarqube application through ingress controller from K8S cluster.
Do you still remember how to fix this?

**Comment by tubushitu** [comment] 2022-08-12 06:23
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project rvc-spring-boot-parent: Unable to execute SonarScanner analysis: Fail to get bootstrap index from server: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

SonarQube server [https://xx.xx.xx..com/sonar] can not be reached
